version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myporto
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: portfolio-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: myporto
      JWT_SECRET: rahasia-super-secret-key-2024
      CLOUDINARY_CLOUD_NAME: dd8ub3wvw
      CLOUDINARY_API_KEY: 684141267414274
      CLOUDINARY_API_SECRET: CYWBymXBC3e4dBSjqAWs-XuPWeI
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "node seed.js & sleep 15 && npm run dev"

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000/api

volumes:
  mysql_data: